[project]
name = "fundoo-notes"
version = "0.1.0"
description = "Fundoo Notes Backend using FastAPI"
authors = [
    { name = "Dikshitha Modi" }
]
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "passlib[bcrypt]",
    "python-jose",
    "python-multipart",
    "pydantic",
]

[tool.uvicorn]
factory = false
